server:
  port: 8090

spring:
  #默认 dev 环境
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: api_route
          uri: http://localhost:8123
          predicates:
            - Path=/**
  redis:
    host: localhost
    port: 6379
    database: 1

# Dubbo 配置
dubbo:
  application:
    name: star-api-admin-consumer
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848