# 端口号，路径前缀
server:
  port: 7529
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
        max-age: 2592000
# 公共配置文件
spring:
  application:
    name: star-api-backend
  # 默认 dev 环境
  profiles:
    active: dev
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  # Redis 配置
  redis:
    database: 0
    host: localhost
    port: 6379
  # session 配置
  session:
    store-type: redis # 分布式 Session
    timeout: 2592000 # 30天过期
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/star_api
    username: root
    password: 1234
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB
  # RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
# 个性化配置
star:
  # 网关 URL
  gateway:
    host: http://localhost:8090
#  # 讯飞星火 密钥
#  ai:
##    地址与鉴权信息  https://spark-api.xf-yun.com/v1.1/chat   1.5地址  domain参数为general
##    地址与鉴权信息  https://spark-api.xf-yun.com/v2.1/chat   2.0地址  domain参数为generalv2
#    hostUrl: https://spark-api.xf-yun.com/v3.1/chat
#    appid: 725adaa4
#    apiSecret: N2YwOWFkYTJhNzA0NWFhMmQ2ZGQ4NmEx
#    apiKey: bab8ee727dbf7b91947298dfb690e184

# Dubbo 配置
dubbo:
  application:
    name: star-api-admin-provider
  protocol:
    name: dubbo
    port: -1
  registry:
    id: nacos-registry
    address: nacos://localhost:8848

## 鱼聪明 密钥配置
#yuapi:
#  client:
#    access-key: 替换为你自己的 access-key
#    secret-key: 替换为你自己的 secret-key

# Mybatis-plus
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)

## 微信相关
#wx:
#  # 微信公众平台
#  # todo 需替换配置
#  mp:
#    token: xxx
#    aesKey: xxx
#    appId: xxx
#    secret: xxx
#    config-storage:
#      http-client-type: HttpClient
#      key-prefix: wx
#      redis:
#        host: 127.0.0.1
#        port: 6379
#      type: Memory
#  # 微信开放平台
#  # todo 需替换配置
#  open:
#    appId: xxx
#    appSecret: xxx
# 对象存储
# todo 需替换配置
#cos:
#  client:
#    accessKey: xxx
#    secretKey: xxx
#    region: xxx
#    bucket: xxx
#aliyun:
#  oss:
#    endpoint: oss-cn-hangzhou.aliyuncs.com
#    urlPrefix: http://nero-api-project.oss-cn-hangzhou.aliyuncs.com
#    accessKeyId: ***********
#    accessKeySecret: **********
#    bucketName: nero-api-project
#    fileHost: files